#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libzmf
Version  : 0.0.2
Release  : 10
URL      : https://dev-www.libreoffice.org/src/libzmf-0.0.2.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libzmf-0.0.2.tar.xz
Summary  : Library for importing and converting Zoner Draw drawings
Group    : Development/Tools
License  : MPL-2.0-no-copyleft-exception
Requires: libzmf-bin = %{version}-%{release}
Requires: libzmf-lib = %{version}-%{release}
Requires: libzmf-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libzmf is a library and a set of tools for reading and converting
Zoner Draw and Zebra file formats.

%package bin
Summary: bin components for the libzmf package.
Group: Binaries
Requires: libzmf-license = %{version}-%{release}

%description bin
bin components for the libzmf package.


%package dev
Summary: dev components for the libzmf package.
Group: Development
Requires: libzmf-lib = %{version}-%{release}
Requires: libzmf-bin = %{version}-%{release}
Provides: libzmf-devel = %{version}-%{release}
Requires: libzmf = %{version}-%{release}

%description dev
dev components for the libzmf package.


%package doc
Summary: doc components for the libzmf package.
Group: Documentation

%description doc
doc components for the libzmf package.


%package lib
Summary: lib components for the libzmf package.
Group: Libraries
Requires: libzmf-license = %{version}-%{release}

%description lib
lib components for the libzmf package.


%package license
Summary: license components for the libzmf package.
Group: Default

%description license
license components for the libzmf package.


%prep
%setup -q -n libzmf-0.0.2
cd %{_builddir}/libzmf-0.0.2
pushd ..
cp -a libzmf-0.0.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683822090
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1683822090
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libzmf
cp %{_builddir}/libzmf-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libzmf/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/zmf2raw
/V3/usr/bin/zmf2svg
/usr/bin/zmf2raw
/usr/bin/zmf2svg

%files dev
%defattr(-,root,root,-)
/V3/usr/lib64/libzmf-0.0.so
/usr/include/libzmf-0.0/libzmf/ZMFDocument.h
/usr/include/libzmf-0.0/libzmf/libzmf.h
/usr/lib64/libzmf-0.0.so
/usr/lib64/pkgconfig/libzmf-0.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libzmf/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libzmf-0.0.so.0
/V3/usr/lib64/libzmf-0.0.so.0.0.2
/usr/lib64/libzmf-0.0.so.0
/usr/lib64/libzmf-0.0.so.0.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libzmf/9744cedce099f727b327cd9913a1fdc58a7f5599
