#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libzmf
Version  : 0.0.2
Release  : 1
URL      : https://dev-www.libreoffice.org/src/libzmf-0.0.2.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libzmf-0.0.2.tar.xz
Summary  : Library for importing and converting Zoner Draw drawings
Group    : Development/Tools
License  : MPL-2.0-no-copyleft-exception
Requires: libzmf-bin
Requires: libzmf-lib
Requires: libzmf-license
BuildRequires : boost-dev
BuildRequires : doxygen
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(zlib)

%description
libzmf is a library and a set of tools for reading and converting
Zoner Draw and Zebra file formats.

%package bin
Summary: bin components for the libzmf package.
Group: Binaries
Requires: libzmf-license

%description bin
bin components for the libzmf package.


%package dev
Summary: dev components for the libzmf package.
Group: Development
Requires: libzmf-lib
Requires: libzmf-bin
Provides: libzmf-devel

%description dev
dev components for the libzmf package.


%package doc
Summary: doc components for the libzmf package.
Group: Documentation

%description doc
doc components for the libzmf package.


%package lib
Summary: lib components for the libzmf package.
Group: Libraries
Requires: libzmf-license

%description lib
lib components for the libzmf package.


%package license
Summary: license components for the libzmf package.
Group: Default

%description license
license components for the libzmf package.


%prep
%setup -q -n libzmf-0.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534636442
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534636442
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libzmf
cp COPYING %{buildroot}/usr/share/doc/libzmf/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/zmf2raw
/usr/bin/zmf2svg

%files dev
%defattr(-,root,root,-)
/usr/include/libzmf-0.0/libzmf/ZMFDocument.h
/usr/include/libzmf-0.0/libzmf/libzmf.h
/usr/lib64/libzmf-0.0.so
/usr/lib64/pkgconfig/libzmf-0.0.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libzmf/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzmf-0.0.so.0
/usr/lib64/libzmf-0.0.so.0.0.2

%files license
%defattr(-,root,root,-)
/usr/share/doc/libzmf/COPYING
/usr/share/doc/libzmf/html/BMITypes_8cpp.html
/usr/share/doc/libzmf/html/BMITypes_8h.html
/usr/share/doc/libzmf/html/BMITypes_8h_source.html
